package app.vanishr.relay;

import java.security.SecureRandom;
import java.util.List;
import java.util.random.RandomGenerator;

final class GoogleUsernames {
    static final List<String> FIRST_WORDS = List.of(
            "amber", "apricot", "azure", "breezy", "bright", "brisk", "calm", "cheerful",
            "clever", "cloudy", "cozy", "crisp", "curious", "dapper", "eager", "emerald",
            "fair", "gentle", "golden", "grand", "happy", "hazel", "honey", "icy",
            "jade", "jolly", "kind", "lively", "lucky", "lunar", "mellow", "mint",
            "misty", "mossy", "nimble", "noble", "olive", "peach", "plum", "polar",
            "quiet", "rapid", "rosy", "round", "rustic", "sandy", "shiny", "silent",
            "silver", "snowy", "soft", "solar", "starry", "steady", "sunny", "swift",
            "tidy", "tiny", "warm", "wild", "wise", "wooden", "woolly", "zesty",
            "abundant", "active", "adept", "airy", "alert", "amiable", "ample", "amused",
            "ancient", "animated", "antique", "aquatic", "arctic", "artistic", "autumn", "balanced",
            "beaming", "beautiful", "benevolent", "bouncy", "brave", "brilliant", "bubbly", "buoyant",
            "candid", "capable", "careful", "caring", "casual", "charming", "classic", "clean",
            "clear", "colorful", "comfy", "content", "copper", "cosmic", "crafty", "creative",
            "crystal", "dainty", "daring", "dazzling", "dear", "delicate", "delightful", "devoted",
            "dreamy", "dynamic", "earnest", "easy", "electric", "elegant", "enchanted", "endless",
            "energetic", "even", "excellent", "excited", "expert", "extra", "fabulous", "faithful",
            "famous", "fancy", "fast", "fearless", "festive", "fiery", "fine", "floral",
            "fluffy", "focused", "fond", "fragrant", "fresh", "friendly", "frosty", "funny",
            "gallant", "generous", "glad", "gleaming", "gliding", "glorious", "glowing", "graceful",
            "gracious", "green", "growing", "handy", "harmonious", "hearty", "helpful", "heroic",
            "honest", "hopeful", "humble", "ideal", "infinite", "jaunty", "joyful", "jubilant",
            "keen", "leafy", "leisurely", "light", "limber", "loyal", "lucid", "lush",
            "magical", "majestic", "marble", "merry", "mighty", "mild", "mindful", "modern",
            "modest", "musical", "neat", "natural", "open", "optimistic", "orange", "ordinary",
            "orderly", "patient", "peaceful", "perky", "playful", "pleasant", "plucky", "polished",
            "precious", "pretty", "proud", "purple", "quick", "radiant", "rainbow", "ready",
            "regal", "relaxed", "reliable", "resilient", "rich", "rising", "roaming", "robust",
            "royal", "ruby", "rugged", "saffron", "sage", "satin", "scarlet", "serene",
            "sharp", "silky", "simple", "sincere", "skillful", "sleek", "smart", "smooth",
            "snappy", "snug", "sparkling", "splendid", "spring", "stable", "starlit", "stellar",
            "still", "strong", "sturdy", "subtle", "super", "sweet", "talented", "tender",
            "thankful", "thoughtful", "thrifty", "tranquil", "trusty", "turquoise", "upbeat", "valiant",
            "velvet", "vibrant", "vivid", "wandering", "watchful", "wavy", "welcoming", "whimsical",
            "willing", "winsome", "witty", "wonderful", "young", "youthful", "zealous", "agile",
            "alpine", "amazing", "angelic", "appreciative", "assured", "attentive", "authentic", "autumnal",
            "beloved", "blissful", "blithe", "blooming", "bold", "bountiful", "braided", "burnished",
            "carefree", "celestial", "central", "cerulean", "cheery", "chestnut", "circular", "cobalt",
            "compact", "confident", "constant", "courteous", "creamy", "crescent", "cuddly", "cultured",
            "cushioned", "daily", "decorative", "dependable", "dimpled", "distinct", "diverse", "dotted",
            "draped", "drifting", "dulcet", "early", "earthy", "effortless", "elastic", "encouraging",
            "enduring", "enjoyable", "entire", "epic", "ethereal", "evergreen", "exalted", "expressive",
            "fabled", "fairytale", "familiar", "fanciful", "faraway", "favorite", "fertile", "fleecy",
            "flexible", "flowing", "flowering", "fluent", "fluttering", "foamy", "folksy", "fortunate",
            "free", "fringed", "frolicsome", "full", "fuzzy", "gemlike", "genuine", "gifted",
            "glassy", "glistening", "glittering", "glossy", "good", "gossamer", "grandiose", "grateful",
            "great", "grounded", "halcyon", "handcrafted", "hardy", "heavenly", "herbal", "hilarious",
            "historic", "homely", "homemade", "honorable", "hospitable", "illuminated", "imaginative", "immense",
            "impressive", "indigo", "industrious", "ingenious", "inspired", "inventive", "iridescent", "ivory",
            "jazzy", "jocund", "jovial", "judicious", "lavender", "leading", "lemon", "lilac",
            "lithe", "linear", "lofty", "luminous", "luxurious", "lyrical", "magnificent", "marvelous",
            "masterful", "measured", "melodic", "melodious", "memorable", "minty", "moonlit", "motivated",
            "mutual", "nacreous", "nearby", "neighborly", "new", "nifty", "notable", "nurturing",
            "observant", "oceanic", "opal", "opulent", "organic", "original", "ornate", "outgoing",
            "outstanding", "pastel", "pearly", "perfect", "persistent", "petite", "picturesque", "pink",
            "pioneering", "placid", "plentiful", "plush", "poetic", "positive", "powerful", "practical",
            "precise", "pristine", "prompt", "protective", "purposeful", "quaint", "quirky", "quilted",
            "red", "refined", "reflective", "refreshing", "relatable", "relaxing", "remarkable", "resolute",
            "resourceful", "resonant", "respectful", "resplendent", "restful", "restorative", "reverent", "rhythmic",
            "rippled", "rolling", "rounded", "rose", "russet", "scented", "scenic", "scholarly",
            "seasonal", "shimmering", "shining", "silken", "silvery", "singing", "skyblue", "slender",
            "smiling", "sociable", "soothing", "soulful", "spacious", "speckled", "spirited", "sprightly",
            "stately", "steadfast", "stippled", "stony", "streamlined", "striped", "stunning", "stylish",
            "successful", "succulent", "summery", "sunlit", "supple", "supportive", "sure", "symmetrical",
            "tactful", "teal", "thriving", "timeless", "tolerant", "topaz", "united", "versatile");
    static final List<String> SECOND_WORDS = List.of(
            "acorn", "badger", "bamboo", "beacon", "birch", "brook", "cactus", "canyon",
            "cloud", "clover", "comet", "crane", "creek", "cricket", "dune", "eagle",
            "elm", "falcon", "feather", "finch", "firefly", "forest", "fox", "garden",
            "gecko", "grove", "harbor", "heron", "hill", "island", "jasmine", "koala",
            "lake", "lantern", "leaf", "maple", "meadow", "meteor", "moon", "otter",
            "owl", "panda", "pebble", "pine", "planet", "pond", "puffin", "quail",
            "rabbit", "raven", "reef", "river", "robin", "rocket", "sparrow", "sprout",
            "stone", "stream", "summit", "sunset", "tiger", "turtle", "willow", "wren",
            "abalone", "albatross", "alder", "almond", "alpaca", "anemone", "antelope", "apple",
            "apricot", "arch", "arrow", "aspen", "aster", "atlas", "aurora", "avocado",
            "azalea", "baboon", "bakery", "balloon", "banana", "banyan", "barn", "barrel",
            "basil", "basket", "bay", "bayou", "bean", "bear", "beaver", "bell",
            "berry", "bicycle", "bison", "blossom", "bluebell", "bluebird", "boat", "bobcat",
            "book", "bottle", "bouquet", "bowl", "branch", "breeze", "bridge", "broccoli",
            "buffalo", "butterfly", "button", "cabin", "camel", "candle", "canoe", "canvas",
            "caramel", "cardinal", "carnation", "carpet", "carrot", "castle", "caterpillar", "cave",
            "celery", "cello", "chameleon", "cherry", "chestnut", "chickadee", "chipmunk", "chocolate",
            "cicada", "cinnamon", "clay", "cliff", "clock", "coconut", "cod", "coffee",
            "colt", "compass", "cookie", "coral", "coriander", "corn", "cosmos", "cotton",
            "cougar", "cove", "crab", "cranberry", "crocus", "crown", "crystal", "cucumber",
            "cup", "cupcake", "cypress", "daffodil", "daisy", "damselfly", "dandelion", "deer",
            "dewdrop", "diamond", "dill", "dolphin", "donkey", "dove", "dragonfly", "driftwood",
            "drum", "duck", "duckling", "earth", "echidna", "egret", "elderberry", "elephant",
            "emerald", "equinox", "eucalyptus", "evening", "fawn", "fern", "fiddle", "fig",
            "fir", "flamingo", "flannel", "flax", "flower", "flute", "fountain", "freesia",
            "frog", "fuchsia", "galaxy", "gazebo", "gem", "geranium", "gerbil", "gibbon",
            "ginger", "giraffe", "glade", "glacier", "globe", "goat", "goldfinch", "goose",
            "gourd", "granite", "grape", "grapefruit", "grass", "grasshopper", "greenfinch", "gull",
            "hamlet", "hammock", "hamster", "hare", "harmony", "harp", "hawk", "hazelnut",
            "heather", "hedgehog", "hibiscus", "holly", "honeybee", "honeysuckle", "hornbill", "horse",
            "huckleberry", "hummingbird", "hyacinth", "iceberg", "iguana", "impala", "iris", "ivy",
            "jackfruit", "jackrabbit", "jaguar", "jay", "jellyfish", "juniper", "kangaroo", "kestrel",
            "kingfisher", "kiwi", "kite", "kitten", "lagoon", "lamb", "larch", "lark",
            "lavender", "leek", "lemur", "lemon", "leopard", "lettuce", "lilac", "lily",
            "lime", "linden", "lion", "lizard", "llama", "lobster", "lotus", "lychee",
            "lynx", "macaroon", "magnolia", "mahogany", "mallow", "mandarin", "mango", "mangrove",
            "marigold", "marmot", "marsh", "melon", "merlin", "mesa", "mimosa", "mist",
            "mole", "mongoose", "moonflower", "moose", "morning", "moth", "mountain", "mouse",
            "mulberry", "mushroom", "mustard", "narwhal", "nebula", "nectarine", "nest", "nettle",
            "nightingale", "nutmeg", "oak", "oasis", "ocelot", "octopus", "okapi", "olive",
            "orchid", "osprey", "ostrich", "oyster", "palm", "papaya", "parrot", "parsnip",
            "partridge", "passionfruit", "pasture", "path", "pavilion", "peach", "peacock", "pear",
            "pelican", "penguin", "peony", "pepper", "peppermint", "persimmon", "petal", "petunia",
            "pheasant", "phoenix", "pickle", "pigeon", "pineapple", "pistachio", "plateau", "plum",
            "plover", "poplar", "poppy", "porcupine", "primrose", "pumpkin", "puppy", "python",
            "quartz", "quill", "quince", "raccoon", "radish", "raspberry", "redwood", "reindeer",
            "rhubarb", "ridge", "ripple", "rosemary", "rowan", "saffron", "salamander", "salmon",
            "sandpiper", "sapphire", "savanna", "scallop", "seahorse", "sequoia", "shallot", "shamrock",
            "shell", "shore", "shrimp", "silverleaf", "skylark", "slope", "snail", "snapdragon",
            "snowdrop", "snowflake", "soybean", "spruce", "squirrel", "star", "starfish", "starlight",
            "starling", "strawberry", "sugar", "sunflower", "swan", "sweetcorn", "sycamore", "tangerine",
            "tansy", "taro", "tea", "teapot", "tern", "thistle", "thyme", "tomato",
            "topaz", "tortoise", "toucan", "trout", "tulip", "tundra", "twilight", "valley",
            "vanilla", "violet", "walnut", "warbler", "waterfall", "waterlily", "wave", "waxwing",
            "weasel", "wheat", "wildflower", "wolf", "wombat", "woodpecker", "woodland", "yarrow",
            "yew", "yogurt", "yucca", "zebra", "zest", "zinnia", "zucchini", "acacia",
            "accordion", "alcove", "amethyst", "anvil", "aquamarine", "arcade", "astrolabe", "auditorium",
            "awning", "bangle", "banjo", "barge", "basin", "baton", "blanket", "boomerang",
            "brass", "bronze", "bungalow", "cabinet", "caldera", "canopy", "capybara", "caribou",
            "carousel", "chalice", "chime", "chronicle", "clarinet", "cobblestone", "constellation", "corgi",
            "courtyard", "crescent", "dapple", "delta", "diadem", "doorway", "domino", "ebony",
            "envelope", "estuary", "fable", "festival", "flagstone", "fjord", "garland", "gemstone",
            "gondola", "gossamer", "hemisphere", "horizon", "ink", "jigsaw", "kaleidoscope", "mandolin",
            "mosaic", "ocarina", "origami", "panorama", "parchment", "porcelain", "sonnet", "tapestry");
    private static final SecureRandom RANDOM = new SecureRandom();

    static String next() { return next(RANDOM); }

    static String next(RandomGenerator random) {
        return FIRST_WORDS.get(random.nextInt(FIRST_WORDS.size())) + "-"
                + SECOND_WORDS.get(random.nextInt(SECOND_WORDS.size())) + "-"
                + random.nextInt(1000, 10000);
    }

    private GoogleUsernames() { }
}
