#cloud-config
package_update: true
package_upgrade: true
ssh_pwauth: false
disable_root: true
packages:
  - ca-certificates
  - curl
  - docker.io
  - docker-compose-v2
  - openssl
  - certbot
  - nftables
  - jq
write_files:
  - path: /etc/security/limits.d/90-vanishr.conf
    permissions: '0644'
    content: |
      * hard core 0
      * soft core 0
  - path: /etc/systemd/coredump.conf.d/90-vanishr.conf
    permissions: '0644'
    content: |
      [Coredump]
      Storage=none
      ProcessSizeMax=0
  - path: /etc/sysctl.d/90-vanishr.conf
    permissions: '0644'
    content: |
      fs.suid_dumpable=0
  - path: /etc/ssh/sshd_config.d/90-vanishr.conf
    permissions: '0644'
    content: |
      PasswordAuthentication no
      KbdInteractiveAuthentication no
      PermitRootLogin no
      MaxAuthTries 3
      X11Forwarding no
      AllowAgentForwarding no
      AllowTcpForwarding no
      AllowUsers vanishradmin
runcmd:
  - [swapoff, -a]
  - [sed, -i, '/^[^#].*[[:space:]]swap[[:space:]]/s/^/#/', /etc/fstab]
  - [systemctl, mask, swap.target]
  - [sysctl, --system]
  - [mkdir, -p, /opt/vanishr]
  - [chown, 'vanishradmin:vanishradmin', /opt/vanishr]
  - [chmod, '0700', /opt/vanishr]
  - [systemctl, enable, --now, docker]
  - [systemctl, reload-or-restart, ssh]